# Generated by Django 4.1.3 on 2022-11-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('masculino', 'masculino'), ('feminino', 'feminino')], max_length=150)),
                ('curso', models.CharField(choices=[('informatica', 'informatica'), ('alimentos', 'alimentos'), ('apicultura', 'apicultura')], max_length=150)),
                ('minicurso', models.CharField(choices=[('1', 'intodução a computação grafica'), ('2', 'introdução a construção de jogos'), ('3', 'realidade virtual'), ('4', 'computação nas nuvens')], max_length=150)),
            ],
        ),
    ]
