# Generated by Django 4.1.3 on 2022-11-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='minicurso',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='opcao1',
            field=models.BooleanField(default=1, verbose_name='intodução a computação grafica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='opcao2',
            field=models.BooleanField(default=1, verbose_name='introdução a construção de jogos'),
            preserve_default=False,
        ),
    ]
