# Generated by Django 4.1.3 on 2022-11-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_inscricao_minicurso_inscricao_opcao1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='opcao3',
            field=models.BooleanField(default=1, verbose_name='realidade virtual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='opcao4',
            field=models.BooleanField(default=1, verbose_name='computação nas nuvens'),
            preserve_default=False,
        ),
    ]
